version: '3.8'
services:
  database:
    image: postgres:13.2-alpine
    container_name: pp-database
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
  migrate:
    build:
      context: .
      dockerfile: docker/migrate.dockerfile
    image: pp-migrate
    container_name: pp-migrate
    entrypoint: ./wait-for pp-database:5432 -t 10 -- migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - database
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    image: pp-app
    container_name: pp-app
    command:
      - ./wait-for
      - pp-database:5432
      - -t
      - '10'
      - --
      - go
      - run
      - github.com/xXxRisingTidexXx/parallel-computing-labs/cmd/lw10
    volumes:
      - ./go.mod:/go/src/app/go.mod
      - ./go.sum:/go/src/app/go.sum
      - ./cmd:/go/src/app/cmd
      - ./internal:/go/src/app/internal
    environment:
      PP_DSN: postgres://postgres:postgres@pp-database:5432/pp?sslmode=disable
    depends_on:
      - database
volumes:
  database:
    name: pp-database
networks:
  default:
    name: pp-default
